CREATE TABLE `tbl_users` (
	`id_user` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(200) NULL DEFAULT NULL COLLATE,
	`patters` LONGTEXT NULL DEFAULT NULL COLLATE,
	`create_at` DATETIME NULL DEFAULT NULL,
	`email` VARCHAR(200) NULL DEFAULT NULL COLLATE,
	`password` BLOB NULL DEFAULT NULL,
	PRIMARY KEY (`id_user`) USING BTREE
);
